### ISSUE TITLE
Existing Bindings not updated with new certificates

### ISSUE THREAD

**Issue by kd8ssq** [webprofusion/certify#308] opened 2018-05-11 20:26 UTC
In v. 3.0.11.30336, when you create a new certificate against a site that has existing bindings (with an old, non-Lets Encrypt cert), the bindings don't get updated with the new Certify cert.  They have to bound manually (the "Re-apply Certificate to Bindings" doesn't work either).  I've had this happen to 3 different certificate registrations across 2 servers.

The log file shows the certificates were bound as they should be, but they aren't.

```
2018-05-11 16:21:25.411 -04:00 [INF] Completed Certificate Request.
2018-05-11 16:21:25.429 -04:00 [INF] Performing Automated Certificate Binding
2018-05-11 16:21:26.779 -04:00 [INF] Completed certificate request and automated bindings update (IIS)
2018-05-11 16:21:27.819 -04:00 [INF] Certificate installed and SSL bindings updated for abc.com
2018-05-11 16:22:49.447 -04:00 [INF] Performing Automated Certificate Binding
2018-05-11 16:22:50.801 -04:00 [INF] Completed certificate request and automated bindings update (IIS)
2018-05-11 16:22:51.350 -04:00 [INF] Certificate installed and SSL bindings updated for abc.com
```

**Comment by kd8ssq** [comment] 2018-05-12 02:11
I’m using Server 2012 R2, IIS 8.5.

The ports are 443 and the host names match exactly in the Certify cert.
Also, SNI is enabled and the IP address on the binding is undefined
(matches any IP).

**Comment by kd8ssq** [comment] 2018-05-12 02:55
I’ll run some more tests on Monday and see if I can narrow down what the
problem may be.

**Comment by kd8ssq** [comment] 2018-05-14 18:02
I pulled out the code used to update the bindings if they already exist and added them to a brand new project so I could do more generic testing without having to generate new certificates.

What I've found is that when the CertificateHash and CertificateStoreName get set, it does take in the existingBinding (https://github.com/webprofusion/certify/blob/3b315738e74d118076428dbc68e6960fec44a79e/src/Certify.Core/Management/IISManager.cs#L587).  But when the commit happens, it nulls out the CertificateHash and blanks out the CertificateStoreName (https://github.com/webprofusion/certify/blob/3b315738e74d118076428dbc68e6960fec44a79e/src/Certify.Core/Management/IISManager.cs#L644).  

I've seen a few references to people having the same problem where the SSL cert is not set, but no resolution.

**Comment by kd8ssq** [comment] 2018-05-14 20:06
Looks like we're not the only ones having this issue: https://github.com/PKISharp/win-acme/issues/371.

Based on that information the following should work:

```
public bool InstallCertificateforBinding(Site site, X509Certificate2 certificate, string host, int sslPort = 443, bool useSNI = true, string ipAddress = null, bool alwaysRecreateBindings = false)
        {
            var store = new X509Store(StoreName.My, StoreLocation.LocalMachine);
            store.Open(OpenFlags.OpenExistingOnly | OpenFlags.ReadWrite);

            using (var iisManager = GetDefaultServerManager())
            {
                if (GetIisVersion().Major < 8)
                {
                    // IIS ver < 8 doesn't support SNI - default to host/SNI-less bindings
                    useSNI = false;
                    host = "";
                }

                var siteToUpdate = iisManager.Sites.FirstOrDefault(s => s.Id == site.Id);

                if (siteToUpdate != null)
                {
                    string internationalHost = host == "" ? "" : ToUnicodeString(host);
                    var existingBinding = (from b in siteToUpdate.Bindings where b.Host == internationalHost && b.Protocol == "https" select b).FirstOrDefault();
                    string bindingSpec = "";

                    if (existingBinding != null)
                    {
                        // save off old binding information
                        bindingSpec = existingBinding.BindingInformation;
                        var bindingAttributes = existingBinding.Attributes;

                        // remove old binding
                        siteToUpdate.Bindings.Remove(existingBinding);
                    }
                    else
                    {
                        //add new https binding at default port "<ip>:port:hostDnsName";
                        bindingSpec = (!String.IsNullOrEmpty(ipAddress) ? ipAddress : "*") +
                            ":" + sslPort + ":" + internationalHost;
                    }

                    var iisBinding = siteToUpdate.Bindings.Add(bindingSpec, certificate.GetCertHash(), store.Name);
                    iisBinding.Protocol = "https";

                    if (useSNI)
                    {
                        try
                        {
                            iisBinding["sslFlags"] = 1; //enable sni
                        }
                        catch (Exception)
                        {
                            // failed to enable SNI
                            store.Close();
                            return false;
                        }
                    }
                }
                else
                {
                    //could not match site to bind to
                    return false;
                }

                iisManager.CommitChanges();
                store.Close();

                return true;
            }
        }
```
https://github.com/webprofusion/certify/blob/3b315738e74d118076428dbc68e6960fec44a79e/src/Certify.Core/Management/IISManager.cs#L566

**Comment by webprofusion-chrisc** [comment] 2018-05-15 01:38
Thanks for doing this research. Can you confirm if the original certificate was in the MY certificate store, or was it in the Web Hosting store? Can you also confirm if you have any web hosting control panel/cpanel type software installed that could have it's own version of the web administration dll in the GAC?

**Comment by kd8ssq** [comment] 2018-05-15 02:25
Chris,

The original very was in the Personal (MY) store on all 4 servers tested.
I also have no custom panel software installed that would have its own web
admin dll.  Really the only things running on the servers are IIS, ISAPI
and Coldfusion.

**Comment by TheOfficeMaven** [comment] 2018-05-17 20:41
I can confirm this one as well. I'm using V4Alpha6 and unless I completely delete the existing binding, it will fail to get updated without an error being thrown about the certificate not being valid (under Windows Server 2016).

BTW, I'm testing this using the "_RE-APPLY CERTIFICATE TO BINDINGS_" button that's located on the "_Show Advanced Options_" -> "_Other Options_" tab (so that I don't have to request a new certificate each time I want to re-apply the bindings for the latest certificate).

**Comment by webprofusion-chrisc** [comment] 2018-05-17 23:58
@TheOfficeMaven so can you confirm that the preview tab in v4 says it will update that binding (not create a new one)? And that the certificate your replacing was just a manually applied certificate.

**Comment by webprofusion-chrisc** [comment] 2018-05-18 00:40
The really weird part of this bug is that it's never been raised as an issue before (for v3 or v4) but now it seems more common (despite v3 being out for a few months). Rather than (or, as well as) changing how we update bindings I'd really like to understand the reason behind the bug. Changing the certificate hash and updating the store on a binding should just work. Do you guys have any restriction in place on what the Local System account is allowed to do?

**Comment by webprofusion-chrisc** [comment] 2018-05-18 00:41
@kd8ssq regrading a pull request, that would be great - it should be against the development repository (v4).

**Comment by kd8ssq** [comment] 2018-05-18 00:51
It is a very weird bug.  I honestly wouldn't have noticed it except for the
fact that I converted almost a dozen sites (across 5 different servers) at
once and noticed a pattern across each conversion.  I have people on my
team still updating additional sites and I've been told even today that
everything works except for the updating of the certificate on the existing
binding.

I have no restrictions set in place on my Local System account.  Like I
said before, I have been able to replicate this on 5 web servers, 1
development web server and my personal computer.

**Comment by kd8ssq** [comment] 2018-05-18 00:53
I would love to find out why it's happening.  Even in the additional
articles I've found of other people having the problem, I have yet to find
out the reason why.  Like you said, updating the hash and store should just
work, but for some reason, when the commit happens, it nulls out those
values.

**Comment by TheOfficeMaven** [comment] 2018-05-18 03:41
The first time I requested a cert in Certify, I already had an existing (non-Let's Encrypt) cert installed on the default website at binding "*:443:". I used the default "Auto" deployment mode, and Certify correctly installed the new Let's Encrypt cert on that very same binding (just as I'd expect it to).

I then waited a few days, dropped down the auto renewal interval in settings, and allowed it to do an auto renewal of the cert. The cert was properly renewed and installed, but the binding was never set to the newer cert (and I don't recall if there was an error or not). So, I went into Other Options and used the "RE-APPLY CERT TO BINDINGS" button, and it just kept failing with an error telling me that the cert was invalid (not installed correctly, or something like that).

Next, I went to the Deployment tab, changed the deployment mode to Single Site, selected the "Binding hostname not specified" option, set use specific IP to "All Unassigned", set use specific port to "443", and saved the changes. It still failed to manually re-apply the binding via the button in Other Options.

When in "Auto" deployment mode, the Preview tab shows:

> 3. Deployment
> •Deploy to hostname bindings matching certificate domains.
> •Add or Update https bindings as required
> 
> Deploying to all matching sites:
> 
> There are no matching targets to deploy to. Certificate will be stored but currently no bindings will be updated.

When set in the deployment mode specified above the Preview tab shows:

> 3. Deployment
> •Deploy to bindings with blank hostname.
> •Deploy to bindings with previous certificate.
> •Add or Update https bindings as required
> 
> Deploying to Site
> 
> Default Web Site
> 
> Action: Add https binding
> Site: Default Web Site
> Binding: *:443: 

However, in either deployment mode, the binding never gets set (automatically nor manually) unless I first go into IIS and manually delete the existing binding beforehand.

> Do you guys have any restriction in place on what the Local System account is allowed to do?

Not as far as I know. It's a stock Windows Server 2016 Standard installation, but it does have the "Windows Server Essentials Experience" server role installed (and the Anywhere Access / Remote Web Access feature turned on and manually configured with my domain name and SSL cert).

**Comment by kd8ssq** [comment] 2018-05-21 14:03
Still have not been able to figure out why this is happening, but I did submit a pull request to the dev channel.

https://github.com/webprofusion/certify/pull/314

Hopefully it helps.

**Comment by webprofusion-chrisc** [comment] 2018-05-22 00:34
@kd8ssq thanks for the PR, I'll review this week - a lot going on currently!

@TheOfficeMaven interesting error about the certificate being invalid, if not solved by a restart this is almost always a problem accessing the certificate private keys. There was an issue in alpha 4 which generated a pfx with an invalid key chain, assume you weren't using that for the certificate before or if you were that you have a new certificate since then.  

In addition we have also seen that in some cases we have to apply a cert twice for it to take effect (in Window Server only, MS were not able to reproduce that bug though), so I'll check we're still doing that.

I think the failure to update your blank hostname binding is a different bug to this one as the configuration (and the Preview) you describe is hostname specific. If your existing binding is (All Unassigned):(blank hostname):443. Auto deployment will not update that (or shouldn't!) as it can't make hostname assumptions about a binding unless you explicitly tell it to also 'Deploy to bindings with blank hostname'. If an existing binding is shown as 'Add new https binding' this is a red flag that the the deployment is going to be correct (it should say 'Update') as it hasn't identified the existing binding. I assume your existing binding does not have a specific IP. Also the binding settings (IP, Port etc) only affect new bindings, updates will only ever get a new certificate assignments.

**Comment by TheOfficeMaven** [comment] 2018-05-22 14:44
Thank you for the information as it was most helpful. I do believe that you are correct in that this is a different bug. I now believe that it is simply a (minor) case sensitivity issue in Certify the web that is not allowing it to locate the existing binding.

I've only ever installed V4Alpha5 and V4Alpha6 on this particular server (so it wouldn't have seen the invalid key chain issue in V4Alpha4). Also, since the server had an existing certificate (for remote.contoso.com) installed the very first time I ran Certify the web (to get a new wildcard *.contoso.com Let's Encrypt certificate), I assume that is why the original certificate deployment worked when I used the "Auto" deployment mode (i.e. it was able to simply update the existing cert). However, I do now understand that I cannot use the "Auto" deployment mode when requesting a fresh certificate seeing as I require a binding without a specified host name.

So... What I believe is happening is this. The Remote Web Access set up wizard in Windows Server Essentials always generates the following bindings in the applicationHost.config file:

```
<bindings>
    <binding protocol="http" bindingInformation="*:80:" />
    <binding protocol="HTTPS" bindingInformation="*:443:" sslFlags="0" />
    <binding protocol="HTTPS" bindingInformation="*:443:MyServer" sslFlags="1" />
</bindings>
```

Note how it uses the upper case "HTTPS" for the binding protocol. Whereas if I delete the existing binding and allow Certify the web to create it, or if I create it manually, then it always uses a lower case "https" protocol instead. Therefore, I believe that Certify the web is simply not able to find the existing binding due to the capitalization of the protocol type.

When I look at the Preview tab, it shows "Add https binding" instead of "Update" as you've mentioned. Therefore, Certify the web is obviously not seeing the existing "*:443:" binding of type "HTTPS". When the renewal takes place the new certificate is obtained, but the existing binding is never updated with it, and the Status tab shows the "_An error occurred installing the certificate. Certificate file may not be valid:_" error (most likely because a biding does already exist when it goes to great the new one). Here's the relevant log file information:

```
2018-05-21 20:08:08.529 -07:00 [INF] Beginning Certificate Request Process: Default Web Site using ACME Provider:Certes
2018-05-21 20:08:08.529 -07:00 [INF] Registering Domain Identifiers
2018-05-21 20:08:09.811 -07:00 [INF] Created ACME Order: https://acme-v02.api.letsencrypt.org/acme/order/<SomeNumbers>/<SomeMoreNumbers>
2018-05-21 20:08:09.826 -07:00 [VRB] Fetching Authorizations.
2018-05-21 20:08:09.904 -07:00 [VRB] Fetching Authz Challenges.
2018-05-21 20:08:10.162 -07:00 [INF] Got dns-01 challenge Certes.Acme.Resource.Challenge
2018-05-21 20:08:10.178 -07:00 [INF] Attempting Domain Validation: *.contoso.com
2018-05-21 20:08:10.178 -07:00 [INF] Registering and Validating *.contoso.com 
2018-05-21 20:08:10.178 -07:00 [INF] Authorization already valid for domain: *.contoso.com
2018-05-21 20:09:11.208 -07:00 [INF] Requesting Certificate via Lets Encrypt
2018-05-21 20:09:13.977 -07:00 [INF] Completed Certificate Request.
2018-05-21 20:09:14.040 -07:00 [INF] Performing Automated Certificate Binding
2018-05-21 20:09:16.341 -07:00 [INF] An error occurred installing the certificate. Certificate file may not be valid: C:\ProgramData\Certify\certes\assets\pfx\c2634851-94ce-49fe-8e3f-3080861a8169.pfx
```

And just as an FYI, you can see how I have the Deployment tab (for the above log) configured [here](https://www.theofficemaven.com/wp-content/uploads/2018/03/RWA_82.png).

If I'm understanding things correctly, those settings "should" get a brand new Let's Encrypt certificate deployed to binding "*:443:" (of protocol type "https"), and then once the minor existing binding discovery bug is corrected, they should also allow the certificate to be automatically renewed and re-deployed back to the same binding. If so, that's exactly what I'm looking for. ;-)

**Comment by TheOfficeMaven** [comment] 2018-05-22 15:02
BTW, I just tested my theory by going in and manually editing the existing binding in the applicationHost.config file, and changing it from "HTTPS" to "https". I then opened Certify the web and used the re-deploy button located on the "Other Options" tab to re-deploy the latest certificate to the existing binding, and it worked! Therefore, it definitely seems to be an "HTTPS" vs "https" protocol naming (capitalization) issue going on.

**Comment by webprofusion-chrisc** [comment] 2018-05-23 12:13
@kd8ssq do you have any bindings set to all-unassigned with no hostname like @TheOfficeMaven ? I'm wondering if you have a 'Default SSL site' or similar setup as this would result in an IP:port binding (even if IP is set to all unassigned, assuming there is only one IP).  I notice in your updated code for binding it removes the old binding, including config, which results in existing SSL bindings which might be shared being deleted too, whereas our old code for updating the binding hash is probably conflicting due to other bindings holding onto the old certificate.

**Comment by kd8ssq** [comment] 2018-05-23 13:31
@webprofusion-chrisc I don't have any default SSL bindings for any of my sites.  Each one has *:443:domain_name.  

Also, in all of my tests with the updated code, the binding started with a shared SSL cert and when it was deleted and re-created, the other sites using the old cert were not affected.

**Comment by webprofusion-chrisc** [comment] 2018-05-23 14:02
@kd8ssq Ok, thanks, there goes my theory :) - still stumped as to why this isn't working for you. I've merged your PR for the binding and I'm now updating it with a few more changes (binding attribute cloning etc). I'm still not convinced it should be necessary to re-create the binding but at the moment I don't have an alternative that would fix the issue.

**Comment by kd8ssq** [comment] 2018-05-23 14:35
@webprofusion-chrisc not a problem.  I really wish we could figure it out.  Thanks for all your work!

**Comment by webprofusion-chrisc** [comment] 2018-07-31 06:44
Closing. Bindings are now updated by re-creating them which should be a resolution to this.

**Closed by webprofusion-chrisc** 2018-07-31 06:44 UTC
Labels: bug
