### ISSUE TITLE
Rate Limit not lifted on paid version 

### ISSUE THREAD

**Issue by icecreamuta** [webprofusion/certify#415] opened 2018-12-25 14:44 UTC
I got message on one of the server as

`"Failed to finalize certificate order:  Error finalizing order :: too many certificates already issued for exact set of domains:"`

So, I bought 100 server version of registration to lifted the limit.
But unfortunately, the message is still showing to me after on Registered Version.

What would be my problem please .

https://community.certifytheweb.com/t/rate-limit-not-lifted-on-paid-version/337

**Comment by webprofusion-chrisc** [comment] 2018-12-26 00:47
Hi, the rate limit is from Let's Encrypt and is telling you you have issues too many certs against a single domain. Happy to give a full refund of you've bought a license for the wrong reasons.

Closing this here as it's a support issue, not a bug.

**Closed by webprofusion-chrisc** 2018-12-26 00:47 UTC
