### ISSUE TITLE
dns-01

### ISSUE THREAD

**Issue by moaeddy** [webprofusion/certify#500] opened 2020-05-16 05:29 UTC
i have a paid version of certify, anytime i try using dns-01 for authorization we got delay (24 hours sometime) and recently we don't even get a certificate for a domain using dns-01 despite creating _acme-challenge TXT record on domain and record is 100% correct. 

Can you advise what might the cause of this? i have been trying to know why its happening, and TXT doesn't take 24hrs to update as we using namecheap domain and hosting is windows server 2019 VPS

**Comment by webprofusion-chrisc** [comment] 2020-05-16 09:06
Thanks, paid users should send support requests to 'support at certifytheweb.com' with a log file from your managed certificate, that way we can check the specifics of your domain. 

Note that the app helps you use Let's Encrypt to acquire certificates, but it's Let's Encrypt that performs the DNS validation etc.

Closing because this is a support request and not a bug.

**Closed as completed by webprofusion-chrisc** 2020-05-16 09:06 UTC
