### ISSUE TITLE
Connections should default to TLS 1.2

### ISSUE THREAD

**Issue by natiki** [webprofusion/certify#69] opened 2017-03-08 10:00 UTC
Hi,

- Certify 0.9.96 - 20170205 Alpha 13
- Windows Server 2012 R2

My guess here is that the TLS version being used by Certify is not 1.2. The server is locked down as follows:

![image](https://cloud.githubusercontent.com/assets/4738140/23698671/8141fdd0-0440-11e7-8758-285e0d9974bf.png)

From what I can see the Winforms app is compiled [against .NET 4.5](https://github.com/webprofusion/certify/blob/master/src/Certify.Winforms/App.config)  which limits you to SecurityProtocolType.Ssl3 | SecurityProtocolType.Tls. You will need to update to .NET 4.6 to get TLS 1.2.

The LetsEncrypt host supports [TLS up to 1.2](https://www.ssllabs.com/ssltest/analyze.html?d=acme-v01.api.letsencrypt.org&hideResults=on). 

Whenever possible the highest TLS version should be used as otherwise Certify will be unusable on hosts locked down for best security.

The stack trace is:

> [20:35] Powershell: Setting Working Directory to C:\ProgramData\ACMESharp\sysVault
> [20:35] Powershell: Initialize-ACMEVault -BaseURI https://acme-v01.api.letsencrypt.org/
> [20:36] Powershell: New-ACMEIdentifier -Dns xxxxxxxxx.net.au -Alias ident276ed172 -Label Identifier:treasure.natiki.net.au
> [20:36] [Error]: System.Management.Automation.CmdletInvocationException: The underlying connection was closed: An unexpected error occurred on a receive. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a receive. ---> System.ComponentModel.Win32Exception: The client and server cannot communicate, because they do not possess a common algorithm
>    at System.Net.SSPIWrapper.AcquireCredentialsHandle(SSPIInterface SecModule, String package, CredentialUse intent, SecureCredential scc)
>    at System.Net.Security.SecureChannel.AcquireCredentialsHandle(CredentialUse credUsage, SecureCredential& secureCredential)
>    at System.Net.Security.SecureChannel.AcquireClientCredentials(Byte[]& thumbPrint)
>    at System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset, Int32 count, Byte[]& output)
>    at System.Net.Security.SecureChannel.NextMessage(Byte[] incoming, Int32 offset, Int32 count)
>    at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
>    at System.Net.TlsStream.CallProcessAuthentication(Object state)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
>    at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
>    at System.Net.PooledStream.Write(Byte[] buffer, Int32 offset, Int32 size)
>    at System.Net.ConnectStream.WriteHeaders(Boolean async)
>    --- End of inner exception stack trace ---
>    at System.Net.HttpWebRequest.GetResponse()
>    at ACMESharp.AcmeClient.RequestHttpGet(Uri uri)
>    at ACMESharp.AcmeClient.Init()
>    at ACMESharp.POSH.NewIdentifier.ProcessRecord()
>    at System.Management.Automation.Cmdlet.DoProcessRecord()
>    at System.Management.Automation.CommandProcessor.ProcessRecord()
>    --- End of inner exception stack trace ---
>    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
>    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
>    at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
>    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
>    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
>    at System.Management.Automation.PowerShell.CoreInvoke[TOutput](IEnumerable input, PSDataCollection`1 output, PSInvocationSettings settings)
>    at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
>    at Certify.PowershellManager.InvokeCurrentPSCommand(Boolean discardErrors)
>

**Comment by webprofusion-chrisc** [comment] 2017-03-08 11:56
Thanks, however unless something has changed overnight I suspect the issue is local to your server. Certify has 1000s of users, even of the Alpha version, and if we just couldn't communicate with Lets Encrypt at all then we'd have seen this before.  

What tool are you using to lockdown your server? Certify has it's own modest lockdown option in the Settings menu but your screenshot looks a whole lot more exhaustive.

**Comment by natiki** [comment] 2017-03-08 12:00
Hi @webprofusion-chrisc,

I think it is local to my installation because the server only supports TLS 1.2. The WinForms app is .NET 4.5 so can only go as high as TLS 1.0.

Lockdown Tool: https://www.nartac.com/Products/IISCrypto

**Comment by webprofusion-chrisc** [comment] 2017-03-08 12:02
I haven't seen a restriction for .net 4.5 regarding the TLS being limited to 1.2 - is that noted somewhere?

**Comment by natiki** [comment] 2017-03-08 12:12
Hi Christopher,

I did not look closely at the code but the following should get you started.

- https://msdn.microsoft.com/en-us/library/system.net.servicepointmanager.securityprotocol(v=vs.110).aspx
- http://stackoverflow.com/questions/42407126/soaphttpclientprotocol-and-tls-1-2-the-client-and-server-cannot-communicate-b

**Comment by webprofusion-chrisc** [comment] 2017-05-09 11:57
Closing - this one appeared to be specific to the server configuration. Feel free to re-open if that's not the case.

**Comment by natiki** [comment] 2017-05-09 12:20
Hi Christopher,

This is not specific only to this host. It applies specifically to having a minimum TLS 1.2 configuration locally on **any host** and the code potentially not supporting it. My references are accurate and should get you started on making sure that the used ciphers are correct. 

And for what it is worth should you ultimately be going to .NET 4.7 then see https://blogs.msdn.microsoft.com/dotnet/2017/04/05/announcing-the-net-framework-4-7/ and in particular the section "TLS Version now matches Windows" as that may affect your implementation again.

So I am hopeful you will address this bug as I still am unable to use the client.

I would be more than happy to test beta releases on my system and provide additional debugging information for you as needed.

**Comment by webprofusion-chrisc** [comment] 2017-05-09 14:01
Reopening. Prepared to do more on this if a resolution can be found, targeting higher versions of .net is a possibility but undesirable.

**Comment by natiki** [comment] 2017-05-11 09:06
Thanks Christopher. I am happy to test alpha builds if you want to try things out.

**Comment by webprofusion-chrisc** [comment] 2017-05-18 03:37
Further to this, TLS1.2 is supported OK in .net 4.5 but needs Server 2008 R2 or higher. Server 2008 needs patching to support TLS 1.2.

**Comment by natiki** [comment] 2017-05-18 09:15
Hi Christonpher,

How do you patch Windows Server 2008 to get TLS 1.2? According to this https://blogs.msdn.microsoft.com/kaushal/2011/10/02/support-for-ssltls-protocols-on-windows/ there is no TLS 1.2 support for Windows Server 2008.

I am running Windows Server 2012 R2 so am unaffected. You got a build for me to test?

**Comment by webprofusion-chrisc** [comment] 2017-05-22 11:37
@natiki Hi, this is now resolved in v2.0.4 onwards.

**Comment by webprofusion-chrisc** [comment] 2017-05-22 11:39
@natiki and yes, server 2008 can't do TLS 1.2 anyway so that's not an issue.

**Closed by webprofusion-chrisc** 2017-05-22 11:39 UTC
Labels: enhancement

**Comment by natiki** [comment] 2017-05-23 02:04
Hi Christoper,

Can you describe how you got SQL Server 2008 SP2 (not R2) to support TLS 1.2?

**Comment by webprofusion-chrisc** [comment] 2017-05-23 02:55
@natiki Hi, my mistake - I took .net patches to equal support (which isn't the case). You can patch .net but you can't patch the underlying Server 2008 OS, so the only option for using TLS 1.2 is Server 2008 R2 onwards.

**Comment by natiki** [comment] 2017-06-22 12:27
Hi Christopher,

Just wanted to say I downloaded the latest 2.x beta today and it worked flawlessly. Thanks heaps.

**Comment by webprofusion-chrisc** [comment] 2017-06-22 12:39
@natiki brilliant, glad to hear it!
