### ISSUE TITLE
Automatically find new domains bind to website

### ISSUE THREAD

**Issue by jLynx** [webprofusion/certify#129] opened 2017-07-11 04:21 UTC
Is there a way to detect new domains added to a website once a certificate has been created?
At the moment whenever I added a new domain to a website I would have to delete the Certify entry and then make a new one for the domain list at the bottom to update with the new domain I have added.

Is there a way to have it automatically find the newly added domains?

Please let me know if I want not clear when trying to explain this.

**Comment by webprofusion-chrisc** [comment] 2017-07-17 09:53
Thanks, I have the exact same problem with my own sites so I understand completely.  Outside of github issues I have a long list of To Do items and this is one of them. The problem is it does need user interaction to resolve, but we should only really need to prompt the user that new domains have been added (or removed) and ask them to confirm. We should also update the website path, because if you move a website in IIS to a different folder Certify won't automatically notice.

**Comment by webprofusion-chrisc** [comment] 2018-03-22 10:52
Closing. The current version has a refresh option.

**Closed by webprofusion-chrisc** 2018-03-22 10:52 UTC
