### ISSUE TITLE
Custom plugin removed after upgrade (Windows)

### ISSUE THREAD

**Issue by pricewatermouse** [webprofusion/certify#583] opened 2021-10-28 14:41 UTC
I made a plugin with some custom Deployment Tasks specific for my application however **my plugin is removed from** `C:\Program Files\CertifyTheWeb\Plugins` **after each automatic update**  (v5.5.5→5.5.6→5.5.7).

Please fix the installer to remove only files it previously installed (that is normal behavior for windows installer -msi) or provide the way to specify search path or special folder for custom plugins.

Thank you

**Comment by webprofusion-chrisc** [comment] 2021-10-29 00:05
All content under C:\Program Files\CertifyTheWeb\Plugins is subject to removal between updates. Can you try adding your plugin to C:\ProgramData\Certify\plugins instead? Then restart the Certify service.

Is your plugin a DNS provider?

**Comment by pricewatermouse** [comment] 2021-10-29 13:50
My plugin is a Deployment Task (implements `Certify.Providers.DeploymentTasks.IdeploymentTaskProvider`)

If I place it in `C:\ProgramData\Certify\plugins` it fails to load  #584 and doesn’t show up in `Edit Deployment Task` dialog
I restarted the `Certify SSL Manager Service` and `Certify.UI`

**Comment by webprofusion-chrisc** [comment] 2021-11-01 09:33
Closing, as overwrite is the intended behaviour. For bug fix/enhancement for plugin loading see #584 - I think you may be the only person who has written their own plugin :)

**Closed as completed by webprofusion-chrisc** 2021-11-01 09:33 UTC
