### ISSUE TITLE
Certify has stopped working

### ISSUE THREAD

**Issue by ictprocz** [webprofusion/certify#58] opened 2017-02-16 09:16 UTC
Hello,
since I have updated Certify to latest version 0.9.96.0 application crash during new certification enrollment. Could you help me please? Thank you,
Petr

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	Certify.exe
  Application Version:	0.9.96.0
  Application Timestamp:	589bd597
  Fault Module Name:	StackHash_9573
  Fault Module Version:	6.2.9200.21941
  Fault Module Timestamp:	5792e533
  Exception Code:	c0000374
  Exception Offset:	PCH_E0_FROM_ntdll+0x000302AC
  OS Version:	6.2.9200.2.0.0.272.33
  Locale ID:	1029
  Additional Information 1:	9573
  Additional Information 2:	9573a4735f24d267abc5884888f27498
  Additional Information 3:	db72
  Additional Information 4:	db729e502852c17ef04dd8741eb56747

**Comment by soundshed** [comment] 2017-02-16 11:46
Hi, what operating system and PowerShell version are you on? What version of .Net framework do you have? Have you updated both the x86 and x64 versions of PowerShell on your system?

Can you confirm that you are running with an administrator account?

**Comment by ictprocz** [comment] 2017-02-16 12:39
Hi, here it is:
Microsoft Windows Server 2012 [Version 6.2.9200]
PowerShell Version    : 4.0 (both versions updated)
.NET Framework 4.6.1

I have previously created certificated (3months ago) with older version of Certify.

**Comment by elmartino** [comment] 2017-02-18 15:05
Same here!

**Comment by itniels** [comment] 2017-02-19 11:26
Same here, I just updated because i wanted to add a new domain, and now it won't get the certificate, it just crashes silently!

MS Windows Server 2012 Essentials.
PowerShell 4.0
.NET 4.6.2
Certify: 0.9.96 20170205 Alpha13

**Comment by itniels** [comment] 2017-02-19 11:43
**Older Version Here**
I have the old version still, so i will just put it up on my website for download here if anyone needs it :)
Version 0.9.85 20160329.Alpha10
Remember to uninstall the previous one first, otherwise you get errors when opening vault!
It will still remembers all the certs.

**NOTE**
With the older version i now get Faield to create PFX File for Certificate! :-/
So it just won't work!

**Disclaimer!**
I am NOT part of the team, i just happend to have the older version laying around ;)

[](https://nielsschmidt.dk/DL/CertifySetup.exe)

**Comment by soundshed** [comment] 2017-02-19 14:03
Ok, I can't reproduce this one win10, server 2008, 2012, 2012r2 or 2016 (most of these are azure servers). So clearly my testing differs from the real world servers you guys are using (my real production server is 2012 r2, also on azure). So can anyone recreate this on an azure vm (or amazon) and give me the steps? Reverting to earlier versions isn't a solution as the older versions had bugs related to renewals (identifier reuse) that would cause problems renewing anyway.

**Comment by soundshed** [comment] 2017-02-19 14:04
This is also a dupe of #57

**Comment by Prerequisite** [comment] 2017-02-19 20:28
@soundshed I've just run the latest version with a remote debugger on my 2016 server, attached is the the console output from visual studio and the exception from the application. It appears to have been caused by [rate limits](https://letsencrypt.org/docs/rate-limits/), so I suspect that the new policy may have something to do with the recent increase of this issue.

[Certify_190217_App.txt](https://github.com/webprofusion/certify/files/786146/Certify_190217_App.txt)
[Certify_190217_VS.txt](https://github.com/webprofusion/certify/files/786145/Certify_190217_VS.txt)

The steps taken were as follows. 

1. User right click on "api.netfence.io (domain tree item)" in "Certify - SSL Certificate Manager (Alpha Version)"
2. User left click on "Delete (domain menu item)"
3. User left click on "New Certificate (button)" in "Certify - SSL Certificate Manager (Alpha Version)"
4. User left click on "Request Certificate (button)" in "Perform Certificate Request"
5. User left click on "Auto create/update IIS bindings (uses SNI) (check box)" in "Perform Certificate Request"
6. CmdletInvocationException: Certificate has not been submitted yet; cannot update status

**Comment by soundshed** [comment] 2017-02-20 02:43
@Prerequisite thank you very much for your effort, so the issue is at the Request Certificate stage, which we then follow with the call to Update Certificate (which is where the exception was firing). 

So the question is, if you get 5 attempts per domain (20 per main domain), per certificate every 7 days, why are we hitting a rate limit? What is the common factor that's causing this to show up - are we all using a lot of subdomains? 

https://letsencrypt.org/docs/rate-limits/

**Comment by itniels** [comment] 2017-02-20 04:31
Using a mix of Top level and subdomains.
i have a total of 14 domains/subdomains with Let's Encrypt.
I just renewed 8 of them on a linux server, and then i went to add a new sub domain (#15) in certify on windows and it would not let me do it.

Could there be a retry hitting the limit somewhere in code?

I have checked out the repo, but i have not had time to look at it yet, and i got 14 errors of missing dependencies i could not resolve! :-/

![image](https://cloud.githubusercontent.com/assets/15611687/23112084/7965c0a8-f72d-11e6-8c68-b53702e66cbe.png)

**Comment by soundshed** [comment] 2017-02-20 06:19
@itniels I need to update the readme, you need to build ACMESharp first, open the solution under /src/lib/ACMESharp and build it, this will restore the nuget packages it requires.

**Comment by itniels** [comment] 2017-02-20 21:00
@soundshed Thankyou :) It is now building and working ;)
I will have a crack at it, and maybe do some code organization etc.
I don't have too much spare time these days with a new job. But i will try and look at it, and have more time this weekend.

I really like Certify, and would love to help as much as i can :)

/Niels

**Comment by soundshed** [comment] 2017-02-20 23:06
@itniels for info, I've started reworking the vault/powershell manager on a separate branch to see if I can remove the powershell dependency altogether. This would simplify deployment for users and make debugging/logging easier. 

The main concern though is that there is currently a bug/side effect somewhere now that's causing this particular issue with requests. The plan was actually to rework the iis request process to use the same process as  the cli (work in progress, have a look at the cli project code in the same solution) - so that automated renewals or manual requests both take the same code path.

**Comment by itniels** [comment] 2017-02-21 04:39
@soundshed Okay :) Sounds very good.
I will try and have a look at it and see if i canget it all setup so i can test it properly, and then find the bug ;)
I will let you know of my progress :-) And we will stay in touch ;)

**Comment by ndouthit** [comment] 2017-02-21 23:50
@soundshed are you planning to reference the ACMESharp DLLs directly instead of PowerShell?

**Comment by soundshed** [comment] 2017-02-23 00:26
@ndouthit so the current version bundles a copy of ACMESharp rather than using the PowerShell gallery module, this further work is an experiment to see if there is a way to still use ACMESharp commands but not invoke them via PowerShell. This will likely require modifications to ACMESharp to avoid code duplication (currently a lot of the logic is within the PowerShell commands themselves).

**Comment by soundshed** [comment] 2017-02-23 00:27
Oops, wrong button. Reopening.

**Comment by mitchelsellers** [comment] 2017-03-15 13:14
I just wanted to chime in here on this one as well.  We are seeing the same issue with the "Certificate has not been submitted yet, cannot update status" error.  In our cause this is a brand new installation, with a brand new set of domains.  So I don't believe it would be at all tied to rate limiting.

Our environment is as follows:

Certify: 0.9.98 - 20170311.Alpha15
Windows: Server 2008 R2, Standard with Service Pack 1
Powershell: 5.0.10586.117

Any thoughts of a workaround?

**Comment by webprofusion-chrisc** [comment] 2017-03-15 14:41
Hi Mitchell, would you be able to send you Vault file to me (email apps {at} webprofusion.com) and I can look at the configuration? There's no good reason for this that I know of so I'm still trying to find some commonality, I'm very keen to understand where the fault is. Your vault file is under c:\programdata\acmesharp\sysvault and is a single file called 00-VAULT. From there I can use it to check the status of each identifier etc with the Lets Encrypt service.

**Comment by JPLiggett** [comment] 2017-04-10 13:08
the latest rev crashes, with both existing vault and new request
I tried the older rev, and that fubar'd the cert issue process.   any chance of a resolution soon?

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	Certify.exe
  Application Version:	0.9.98.0
  Application Timestamp:	58c3aaa1
  Fault Module Name:	StackHash_9811
  Fault Module Version:	6.2.9200.21815
  Fault Module Timestamp:	56eaff87
  Exception Code:	c0000374
  Exception Offset:	PCH_36_FROM_ntdll+0x00040A6C
  OS Version:	6.2.9200.2.0.0.272.7
  Locale ID:	1033
  Additional Information 1:	9811
  Additional Information 2:	9811e3dc0d7f8178da4187d4d22df6bd
  Additional Information 3:	4e21
  Additional Information 4:	4e2150a624cad07335efde58545621aa

**Comment by webprofusion-chrisc** [comment] 2017-04-11 04:57
@jpliggett can you confirm that the your website works without redirection over standard http? This is required for the current http-01 domain verification method we are using with Lets Encrypt.

**Comment by elmartino** [comment] 2017-04-24 09:23
I got the same problem i think.. It's crashing on windows server 2012 after cert request: 

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	Certify.exe
  Application Version:	0.9.98.0
  Application Timestamp:	58c3aaa1
  Fault Module Name:	StackHash_b3e1
  Fault Module Version:	6.2.9200.21941
  Fault Module Timestamp:	5792e533
  Exception Code:	c0000374
  Exception Offset:	PCH_68_FROM_ntdll+0x000302AC
  OS Version:	6.2.9200.2.0.0.272.7
  Locale ID:	1033
  Additional Information 1:	b3e1
  Additional Information 2:	b3e18ed70327fcad7775dc4b25ba4d73
  Additional Information 3:	7e3f
  Additional Information 4:	7e3fb289637c4c19e6ccbb4ef4ed92e2

**Comment by webprofusion-chrisc** [comment] 2017-05-01 11:33
@elmartino - yes the redirection is very likely the problem in your case. Future versions of Certify will likely help work round this but to start with you need to make the http version of your site accessible, at least for the lets encrypt service to fetch from your site (check your IIS logs).

**Comment by elmartino** [comment] 2017-05-02 09:13
Unfortunately disabling the http -> https redirect isn't the solution. Still crashing.

**Comment by webprofusion-chrisc** [comment] 2017-05-03 12:22
Hi, can you try out the new alpha version of Certify 2.0? https://certify.webprofusion.com/downloads/certifysetup2.0.0-alpha.exe

Many of the features have been re-written and I'd expect at least a better error message if there's a configuration problem, that said - it's an alpha version so see how you get on. This new version supports SAN and auto renewal.

**Comment by elmartino** [comment] 2017-05-03 13:16
great, will try!

**Comment by elmartino** [comment] 2017-05-04 11:02
It's working a lot better then the previous version :-) thanks! There are some bugs, like missing scrollbar and anoying please save messages when there is nothing to save, but it works for requesting the certs. (even when i use redirects)

**Comment by elmartino** [comment] 2017-05-04 12:13
![error](https://cloud.githubusercontent.com/assets/23487045/25702947/bfaf72cc-30d3-11e7-8269-defefc1e0672.png)

Hi, i get this error. Is this limitation a Certify error or a let's encrypt error?

**Comment by webprofusion-chrisc** [comment] 2017-05-04 12:22
@elmartino thanks for the feedback, the error about the 100 DNS names is definitely a Lets Encrypt error - your hitting the 100 names for cert limit: https://letsencrypt.org/docs/rate-limits/

The only way round that would be to define 2 or more managed sites with different domains selected and split the request between them. That could be difficult to manage.

**Comment by elmartino** [comment] 2017-05-04 12:30
Thanks for the suggestion. This is working indeed! I split the www and non www and then i'm not reaching the 100 (yet). It would be great if there could be some kind of filter or search box in the domains list. 

But this is already a huge improvement with the possiblity of SAN's. Before i had to request every cert every 3 months.. Now i only have to request 2 certs every 3 months!!

Great work!

**Comment by webprofusion-chrisc** [comment] 2017-05-04 12:42
@elmartino Yes, if you configure the auto renew it creates a windows scheduled task that attempts to renew all certs (older than 7 days). That functionality is still a little unproven in production but does however appear to be working for me. You can check the logs under c:\programdata\certify\ - In addition, about half an hour ago I refreshed the v2 alpha version (same link) to better format the managed sites expiry dates etc.

**Comment by webprofusion-chrisc** [comment] 2017-05-09 12:00
Closing. v2 alpha is now released.

**Closed by webprofusion-chrisc** 2017-05-09 12:00 UTC
Labels: bug, duplicate, help wanted
