### ISSUE TITLE
UI freezes when loading a large number of bindings

### ISSUE THREAD

**Issue by vulwaowf** [webprofusion/certify#197] opened 2017-11-03 19:01 UTC
1. Click on New Certificate.
2. In the drop down "Select IIS Site", pick a site with alot of bindings*
3. The UI freezes loading the bindings (20-30 seconds)

* I have approximately 895 bindings in applicationHost.config.  To reproduce you can manually enter a random set of third level domains in your applicationHost.config file to verify the issue.  IIS needs to be restarted to load the new bindings.

Example of a binding in applicationHost.config
<binding protocol="http" bindingInformation="*:80:thirdlevel.domain.com" />

**Comment by webprofusion-chrisc** [comment] 2017-11-04 06:19
Thanks, this is a duplicate of #177

**Closed by webprofusion-chrisc** 2017-11-04 06:19 UTC
