### ISSUE TITLE
Certify SSL Manager Service no longer starts after Upgrade to 5.6.0

### ISSUE THREAD

**Issue by criwayc** [webprofusion/certify#593] opened 2021-12-15 09:30 UTC
The Windows service no longer starts and the following error can be found in the Windows EventLog:

--------------------snip--------------------
Service cannot be started. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AggregateException: One or more errors occurred. ---> System.EntryPointNotFoundException: Unable to find an entry point named 'SIfcfad09d1b0a60ec' in DLL 'SQLite.Interop.dll'.
   at System.Data.SQLite.UnsafeNativeMethods.sqlite3_open_interop(Byte[] utf8Filename, Byte[] vfsName, SQLiteOpenFlagsEnum flags, Int32 extFuncs, IntPtr& db)
   at System.Data.SQLite.SQLite3.Open(String strFilename, String vfsName, SQLiteConnectionFlags connectionFlags, SQLiteOpenFlagsEnum openFlags, Int32 maxPoolSize, Boolean usePool)
   at System.Data.SQLite.SQLiteConnection.Open()
   at System.Data.Common.DbConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ...
--------------------snip--------------------

OS: Windows Server 2019

After downgrading to v5.5.7 everything works again.

**Comment by webprofusion-chrisc** [comment] 2021-12-15 09:44
Thanks, Dupe of #592

**Closed as completed by webprofusion-chrisc** 2021-12-15 09:44 UTC
