### ISSUE TITLE
Certificate not selected after successful request

### ISSUE THREAD

**Issue by nazwa** [webprofusion/certify#82] opened 2017-05-09 21:14 UTC
Hey guys

First of all - amazing work. This tool is going to be amazing once it's finished. 

I gave it a go, created a new certificate with no trouble aaannnd... it didn't work! IIS showed no certificate selected for the https binding. No errors, nothing. Had to manually pick it from the dropdown.

- Simple dev page with one domain 
- Preexisting http and https bindings.
- App pool shared with another site

```
2017-05-09 21:57:38.388 +01:00 [Information] Beginning Certificate Request Process: xxx
2017-05-09 21:57:38.591 +01:00 [Information] Attempting Domain Validation: xxx
2017-05-09 21:58:04.972 +01:00 [Information] Beginning Certificate Request Process: xxx
2017-05-09 21:58:05.175 +01:00 [Information] Attempting Domain Validation: xxx
2017-05-09 21:58:11.741 +01:00 [Information] Completed certificate request and automated bindings update (IIS)
```

I'd love to help you somehow figure this out, but now sure how can I provide more details?

**Comment by webprofusion-chrisc** [comment] 2017-05-09 23:32
Thanks for reporting this, very much appreciated. It seems like it got pretty close but at the step it creates the bindings it got lost and apparently thought it had been successful. Would you have a few sites setup in IIS and could any of them have the same binding but be stopped? What OS are you on? It could be helpful if you send a zip of your c:\programdata\certify folder to apps@webprofusion.com - that might show something.

**Comment by webprofusion-chrisc** [comment] 2017-05-10 00:23
@nazwa just had a thought: was your existing https binding bound to a specific IP other than the default and would it have already used SNI?

**Comment by nazwa** [comment] 2017-05-10 09:06
Hi @webprofusion-chrisc 

Thanks for getting back to me. 

1. There are about 50 unique sites, but I'm certain the domain I tried was linked to only the one.
2. Default port, any IP
3. SNI active
4. Windows Server 2012 R2
5. I'll send that folder a bit later today

**Comment by nazwa** [comment] 2017-05-12 17:24
Small update: Certify worked totally fine on a new site, which didn't have an existing https binding.

**Comment by webprofusion-chrisc** [comment] 2017-05-13 10:48
@nazwa thanks, got the logs you sent through, so far nothing obvious - still investigating.

**Comment by terbolous** [comment] 2017-11-15 22:28
Fairly certain I'm facing the same issues, been having sites that suddenly starts sending the wrong cert because none is selected. 

No errors in any logs I've found. Is it possible to increase verbosity somehow?

**Comment by webprofusion-chrisc** [comment] 2017-11-16 00:08
@terbolous can you confirm you are on the latest version of the app? That part is really important, in particular how we identify which IIS site to update bindings for has changed since this bug was originally opened, which could make a difference. 

The primary reason for seeing the wrong site is a static IP binding taking precedence over (all unassigned). You can try deleting the https binding in IIS and adding it again or to uncheck (then save) and re-check Server Name Indication on the binding in IIS.

**Comment by terbolous** [comment] 2017-11-16 08:49
I'm using version 2.1.25.20711 and none of my sites bind to an IP

**Comment by webprofusion-chrisc** [comment] 2017-11-16 08:57
If you edit the https binding can you select the correct certificate or was the new certificate just not created? Do you use a different account to run the auto renewal (different to the interactive user for the GUI?).

**Comment by terbolous** [comment] 2017-11-16 09:13
I can select the correct certificate. Both the interactive usage and auto renewal is done with the same account (Administrator)

**Comment by webprofusion-chrisc** [comment] 2017-11-16 09:49
Ok, and once you have selected the correct certificate the site works OK?

**Comment by terbolous** [comment] 2017-11-16 09:56
Yes. I've not used certify for very long yet, but I believe I've experience a few occurences where one site has lost it's certificate binding while working on another site. 

But let me see if this reoccurs before thinking any more about it

**Comment by webprofusion-chrisc** [comment] 2017-11-16 10:39
Ok, no problem. One other thing to add is if you have used other tools like letsencrypt-win-simple on the same server they can also create conflicting updates to be aware of, in particular certificate binding updates.

**Comment by webprofusion-chrisc** [comment] 2018-03-14 00:36
Closing. Please re-open if this is still confirmed and reproducible.

**Closed by webprofusion-chrisc** 2018-03-14 00:36 UTC
Labels: bug, v2 beta
