### ISSUE TITLE
Misleading error message upon issue with handler webconf setting on IIS

### ISSUE THREAD

**Issue by StefanEgo** [webprofusion/certify#260] opened 2018-02-16 10:52 UTC
Environment:
- IIS 8.5
- Certify 3.0.11

When trying to set up a new certificate (using the http-01 challenge type), I'm being presented with the following error:

Challenge Test Failed
Configuration Check Failed:
Config checks failed to verify [URL] is both publicly accessible and can serve extensionless files e.g. [URL]/.well-known/acme-challenge/configcheck
OK   

If I disable the "Perform challenge response config checks" setting and request the certificate, I'm getting the following LE error in the logs:
"2018-02-16 11:45:52.417 +01:00 [INF] Domain validation failed: [URL]
[type, urn:acme:error:unauthorized]
[detail, Invalid response from [URL]/.well-known/acme-challenge/[...]: "<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http"]
[status, 403]"

Opening "[URL]/.well-known/acme-challenge/[...]" in the webbrowser brings up the following error:
"error code: "0x80070021"

This configuration section cannot be used at this path. This happens when the section is locked at a parent level. Locking is either by default (overrideModeDefault="Deny"), or set explicitly by a location tag with overrideMode="Deny" or the legacy allowOverride="false".

 \\?\[local path]\.well-known\acme-challenge\web.config"
See [1] for related infos.

The config source points to the handlers node in that web.config file.

Checking through our web server configuration, it turned out that indeed the handler note to not be permitted to be overridden. Changing that webserver setting then resolved the certificate challenge problem.

Now I'm wondering a few things here:
1. Back around Certify version <3.x I already requested (successfully) a certificate using certify for another webpage running at the same server. So I take it back then the http-challenge was done slightly differently not running into the configuration issue we were facing here, right?
2. The certify challenge test error message seems to be quite misleading (or maybe it's just me not getting the connection to the actual configuration issue?). If that's right, maybe the error message could be improved and/or a specific test for this misconfiguration could be added to point directly to what's wrong?
3. Renewing already existing certificates doesn't seem to be an issue even with the misconfiguration at hand. I take it that for certificate renewals the handler doesn't need to be overridden. Is this correct?

[1] https://blogs.msdn.microsoft.com/webtopics/2010/03/08/troubleshooting-http-500-19-errors-in-iis-7/ (scenario 7)

**Comment by webprofusion-chrisc** [comment] 2018-02-17 01:05
Hi, thanks for raising this. 

The error message is basically correct, because your configuration does not allow validation to complete successfully. However as you noted, the root cause is that we have tried to configure a handler for extensionless files (Let's Encrypt challenge validation files have an filename without an extension) and your server is configured to disallow that, that's usually the case for server that do web hosting for untrusted apps that customer may provide, which I'm assuming is the case here otherwise you don't need that setting.

If you remove the '<clear />' element from the web.config under ./well-known/acme-challenge that should then work for you and if not you can customize that until you get the .well-known/acme-challenge/configcheck file to server properly. From there on renewals will work for that site and you can copy that web.config for other sites as required.

The long term plan here is to offer an option of custom web.config in the managed site settings, as well as possibly having a default web.config you can change for all sites.

**Comment by webprofusion-chrisc** [comment] 2018-02-17 01:06
.. The other possibility is that we detect when config override is disallowed and adapt to that.

**Comment by StefanEgo** [comment] 2018-02-19 10:13
This sounds like a reasonable idea, if this is the default configuration of IIS (which I donno; though I'd guess so, since I don't recall us having changed this particular setting explicitly) since I take it that quite a few others would then run into the same issue.

As per your detailed explanation on what's going on (thanks for that btw), it sounds like another approach would be to run two separate tests in one go: first the current one and then one simply without the special registered handler, if the previous test fails. This would then also cover other issues with the customized handler on specific configurations (not that I'd be aware of any other reason for this not to work).

**Comment by PKrause79** [comment] 2018-07-11 12:04
_If you remove the '' element from the web.config under ./well-known/acme-challenge that should then work for you and if not you can customize that until you get the .well-known/acme-challenge/configcheck file to server properly._ 

I don´t understand what @webprofusion-chrisc means by "the '' element" - is that a typo? 

Background: I have the same issue on my reverse proxy server and trying to fix it. The reverse-Proxy was configured via IIS managment and is running great (port 80 is redirected to my localhost port 5000 webserver) and I now want to encrypt the port 80 page with Letsencrypt the first time of my life. 

Here is my web.config plced in wwwroot, to suppress forwarding of the ACME check to port 5000 webservice by the "LetsEncrypt"-rule and moreover I combined the web.config contents I found in the \.well-known\acme-challenge\web.config-template :

<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <system.webServer>
    <validation validateIntegratedModeConfiguration="false" />
    <staticContent>
        <mimeMap fileExtension="." mimeType="text/json" />
    </staticContent>
    <rewrite>
            <rules>
                <rule name="LetsEncrypt" stopProcessing="true">
                    <match url=".well-known/acme-challenge/*" />
                    <conditions logicalGrouping="MatchAll" trackAllCaptures="false" />
                    <action type="None" />
                </rule>
	    </rules>
    </rewrite>
  <handlers>
      <clear />
    <add name="StaticFile" path="*" verb="*" type="" modules="StaticFileModule,DefaultDocumentModule,DirectoryListingModule" scriptProcessor="" resourceType="Either" requireAccess="Read" allowPathInfo="false" preCondition="" responseBufferLimit="4194304" />
  </handlers>
  </system.webServer>
  <system.web>
    <authorization>
      <allow users="*" />
    </authorization>
  </system.web>
</configuration>

I am getting the error: Config checks failed to verify http://qdanext.de is both publicly accessible and can serve extensionless files e.g. http://qdanext.de/.well-known/acme-challenge/configcheck

Any help? Thx in advance!

**Comment by webprofusion-chrisc** [comment] 2020-05-13 05:47
Closing - deprecated functionality. User should use the default built-in http challenge server instead of IIS to handle http validation.

**Closed by webprofusion-chrisc** 2020-05-13 05:47 UTC
Labels: enhancement
