### ISSUE TITLE
leftover acme_challenge records on cloudflare

### ISSUE THREAD

**Issue by perler** [webprofusion/certify#565] opened 2021-07-02 07:53 UTC
certifytheweb leaves a lot of acme_challenge TXT records on cloudflare DNS and consequently failes to renew the certificate:

`2021-07-01 19:21:23.634 +02:00 [ERR] DNS update failed: Cloudflare DNS API :: Could not add dns record _acme-challenge.domain.com to zone 0a6f34ae9******. Result: BadRequest - {"result":null,"success":false,"errors":[{"code":81057,"message":"Record already exists."}],"messages":[]}`

there is a chaneglog note in 5.4.0

> DNS: Cloudflare provider should not error if TXT record already exists

which would help with the immediate problem of not renewing the certificate, but it doesn't seem to work. also, certifytheweb should clean up after itself, shouldn't it?

**Comment by webprofusion-chrisc** [comment] 2021-07-02 09:01
HI, Pat, yes indeed it should, and normally does. I can confirm that in my own testing the Cloudflare provider is creating and deleting TXT records normally, but I need to double check the behavior if the TXT record already exists. Looking at the code I think we only cope with the TXT record existing and having the same value.

Are you seeing this universally (Certify cannot delete any TXT records at all?) or just on certain zones?

Can you review https://docs.certifytheweb.com/docs/dns/providers/cloudflare and double check that your API token permissions are correct? See https://dash.cloudflare.com/profile/api-tokens and check that it looks like this:

![image](https://user-images.githubusercontent.com/2445502/124248846-d78d5900-db55-11eb-95d7-43445a37875b.png)

**Comment by webprofusion-chrisc** [comment] 2021-07-02 09:22
As suspected the attempt to add a record does fail if the TXT record exists with a different value. Here is an updated test version of the provider: https://certifytheweb.s3.us-east-1.amazonaws.com/downloads/test/Plugin.DNS.Cloudflare.zip 

To try it you would extract the zip and copy the DLL over the existing one in C:\Program Files\CertifyTheWeb\Plugins then restart the Certify background service and the UI.

Note that this will still fail if your API key just doesn't have permission to delete records.

**Comment by perler** [comment] 2021-07-02 09:40
you forgot to make the download public on S3..

**Comment by webprofusion-chrisc** [comment] 2021-07-03 05:27
Ha, yes indeed I did forget. The tool I use used to set that automatically, I suppose it's more secure now at least.

**Comment by perler** [comment] 2021-07-03 09:04
mh.. I don't see any change. stopped the service, copied the .dll, started it.
'02.07.2021  17:14            27.648 Plugin.DNS.Cloudflare.dll'

same log result:

`2021-07-03 10:50:32.115 +02:00 [INF] Cloudflare DNS API :: Could not add dns record _acme-challenge.domain.cc to zone 0a6f34a.... Result: BadRequest - {"result":null,"success":false,"errors":[{"code":81057,"message":"Record already exists."}],"messages":[]}
2021-07-03 10:50:33.350 +02:00 [INF] Cloudflare DNS API :: Could not add dns record _acme-challenge.domain.cc to zone 0a6f34a.... Result: BadRequest - {"result":null,"success":false,"errors":[{"code":81057,"message":"Record already exists."}],"messages":[]}
2021-07-03 10:50:33.350 +02:00 [INF] Performing Post-Request (Deployment) Tasks..
2021-07-03 10:50:33.394 +02:00 [INF] Task [Export Certificate] :: Task is enabled but will not run because primary request unsuccessful.
2021-07-03 10:50:33.395 +02:00 [INF] Task [Export Key] :: Task is enabled but will not run because primary request unsuccessful.
2021-07-03 10:50:33.395 +02:00 [INF] Export Certificate :: Task is enabled but will not run because primary request unsuccessful.
2021-07-03 10:50:33.396 +02:00 [INF] Export Key :: Task is enabled but will not run because primary request unsuccessful.
2021-07-03 10:50:33.396 +02:00 [INF] Cloudflare DNS API :: Could not add dns record _acme-challenge.domain.cc to zone 0a6f34a.... Result: BadRequest - {"result":null,"success":false,"errors":[{"code":81057,"message":"Record already exists."}],"messages":[]}`

**Comment by perler** [comment] 2021-07-03 09:25
I just had another look at the logs and I am not quite sure if the problem isn't a bit deeper. here's the situation:

we create a certificate for multiple TLDs like this:

domain.com
*.domain.com
domain.cc
*.domain.cc

and so on for 5 TLDs.

the _acme record in the log is not in the domain.cc but in the domain.com. I am not sure if this is correct or not, but now we have some dozen _acme-challenge.domain.cc records in domain.com. Also, I had similar records, but only two in domain.cc which I deleted manually..

**Comment by webprofusion-chrisc** [comment] 2021-07-04 07:19
So I'm guessing you currently have multiple authorization configs defined (5?) each with a domain match rule to match the configuration to the correct domain. If the record gets created in the wrong zone you have accidentally specified the wrong Zone ID. Note that there is a bug in the current version of the app (fixed in the next release) where if you add multiple new auth configs the last one incorrectly copies it's values to all the other new ones. This is probably what has happened.

Please review each of your configurations to ensure they are using the correct cloudflare Zone ID for each domain.

Use the Preview tab to see for each identifier the auth configuration which will be used.

Regarding the plugin update, if you browse to C:\Program Files\CertifyTheWeb\Plugins can you confirm the Cloudflare dll has a different date to all the other plugins and **that the Certify background service has been restarted**

**Comment by perler** [comment] 2021-07-04 15:05
re installing the changed .dll: yes, it's being used, I did exactly as you described.

re the certificate, two things: we have all domains under one cloudflare account, so there's just one authentication configuration. also, we have just _one_ certificate with all domains.

the other thing, and this may be the problem in the end: we use for the websites the cloudflare ssl certificate, could this prevent letsencrypt from creating it's own certificate? (we need it for mail and stuff..)

**Comment by webprofusion-chrisc** [comment] 2021-07-14 06:02
Sorry I missed your reply, our support ticket helpdesk system is much better for support conversations so I'd recommend using that for important stuff.

In cloudflare you will have a zone for each domain, each one will have a bunch of DNS records. Each zone ID is different, so `domain.com` and `domain.cc` are two different domains (and two different zones), this means you need two authorization configurations (under the apps Authorization config), one to match each zone. The app then uses the Zone ID (not the domain) to update the TXT records. If you zone ID is wrong then the TXT records will be created/deleted under the wrong domain.

**Comment by perler** [comment] 2021-07-14 06:09
Ok, but this seems to have changed somewhere along the releases. The
configuration with just one authorization config created the certificate
just fine there months ago but stopped working.

We just switched to the cloudflare certificates so, we are good now.

**Closed as completed** 2021-07-14 07:54 UTC
