### ISSUE TITLE
Auto renew bug? "An error occurred installing the certificate. Certificate file may not be valid"

### ISSUE THREAD

**Issue by glat** [webprofusion/certify#370] opened 2018-09-29 07:13 UTC
We host about 270 websites on IIS 8.5. SNI is enabled and all websites uses "All unused IP".

Every two or three days I must open Certify and request a new certificate manually for several websites because they fail the renew. The log end with the error in subject and the website in Certify list of managed certificates becames red.

See screenshot:

![senza-titolo-1](https://user-images.githubusercontent.com/569200/46242321-ae00db00-c3c7-11e8-8ea0-34e3e1a7cbf5.png)

If I do not request a new certificate when It becames red after several days it can expires and get browser error about expiration. Of course manual requesting works fine.

**Comment by webprofusion-chrisc** [comment] 2018-09-29 07:37
You also mentioned that the certificates eventually expire - it should go from orange to red once it has failed to renew a few times, thereafter (if enabled) it will email you to tell you that it's failing. The default renewal interval (days between fetching a new certificate and then attempting to renew it again) is 14 days, which leaves a couple of months to address failed renewal notifications before the certificate expires.

**Comment by webprofusion-chrisc** [comment] 2018-09-29 08:11
Another thing to check is if there certificates are actually being stored ok (in the computer Certificate Manager, under Personal). Looking at the code now this error message can result from either the PFX file being invalid in some way (which it probably isn't) or from a problem updating the binding in IIS (this is probably the real problem). IIS can occasionally throw errors related to updating bindings (which we are not logging and should be) especially if many bindings are being updated in quick succession - this is most likely because IIS needs time to save it's  config after we have asked it to make the change. We do have an artificial delay to allow time for saving but with many websites or slow disk this just might not be enough time. This would also explain why it works when you do it manually (auto renew and manual are the same, it's just that auto-renew will do many pending requests)

**Comment by glat** [comment] 2018-09-29 08:50
Restarting the Certify SSL Manager background service does not help. This behaviour is from several weeks. At least all time by using 4.0.8 (from day 1).

I never saw orange certificates in list. They go from green to red. At the moment I'm preventing expiration by requesting manually new certificates but it's time expensive and boring because it works only one by one (read later about this).

Certificates are stored in Personal (of the SYSTEM account, because background service runs as SYSTEM).

According to the time needed to save bindings in IIS I think it's the real cause because even manually I've to request only one certificate at time. When I request two or three certificates in the same moment some of them gives error.

The cause can be IIS config file which is big due to the number of websites.

What about to renew them one by one in a queue?

P.s. I sent you a PFX, but I think it's correct.

**Comment by webprofusion-chrisc** [comment] 2018-09-30 11:44
Thank you, on further investigation I think we need to add a retry to the IIS binding stage with increasing delay between attempts. This will be added shortly.

The reason I mention Orange labels is that your screenshot includes them (on the left side list of Managed Certificates). After a few attempts these will go red, the 'Renewal Failure' heading will always be red.

**Comment by glat** [comment] 2018-10-01 09:29
Just to be complete, when I request two or more certificates in UI at same time I got this exception (usually only one request has been completed without exception):

(sorry, I use italian language system)

2018-10-01 11:24:55.289 +02:00 [INF] WEB_www.DUMMY.com: Request failed - La chiave specificata non era presente nel dizionario. System.Collections.Generic.KeyNotFoundException: La chiave specificata non era presente nel dizionario.
   in System.ThrowHelper.ThrowKeyNotFoundException()
   in System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   in Certify.Providers.Certes.CertesACMEProvider.<CompleteCertificateRequest>d__24.MoveNext()
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in Certify.Management.CertifyManager.<CompleteCertificateRequestProcessing>d__11.MoveNext()
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in Certify.Management.CertifyManager.<PerformCertificateRequestProcessing>d__10.MoveNext()
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in Certify.Management.CertifyManager.<PerformCertificateRequest>d__7.MoveNext()
2018-10-01 11:24:55.290 +02:00 [INF] WEB_www.studiomormile.it: Request failed - La chiave specificata non era presente nel dizionario. System.Collections.Generic.KeyNotFoundException: La chiave specificata non era presente nel dizionario.
   in System.ThrowHelper.ThrowKeyNotFoundException()
   in System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   in Certify.Providers.Certes.CertesACMEProvider.<CompleteCertificateRequest>d__24.MoveNext()
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in Certify.Management.CertifyManager.<CompleteCertificateRequestProcessing>d__11.MoveNext()
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in Certify.Management.CertifyManager.<PerformCertificateRequestProcessing>d__10.MoveNext()
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in Certify.Management.CertifyManager.<PerformCertificateRequest>d__7.MoveNext()
2018-10-01 11:24:55.306 +02:00 [ERR] Certificate request process failed: System.Collections.Generic.KeyNotFoundException: La chiave specificata non era presente nel dizionario.
   in System.ThrowHelper.ThrowKeyNotFoundException()
   in System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   in Certify.Providers.Certes.CertesACMEProvider.<CompleteCertificateRequest>d__24.MoveNext()
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in Certify.Management.CertifyManager.<CompleteCertificateRequestProcessing>d__11.MoveNext()
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in Certify.Management.CertifyManager.<PerformCertificateRequestProcessing>d__10.MoveNext()
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in Certify.Management.CertifyManager.<PerformCertificateRequest>d__7.MoveNext()
System.Collections.Generic.KeyNotFoundException: La chiave specificata non era presente nel dizionario.
   in System.ThrowHelper.ThrowKeyNotFoundException()
   in System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   in Certify.Providers.Certes.CertesACMEProvider.<CompleteCertificateRequest>d__24.MoveNext()
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in Certify.Management.CertifyManager.<CompleteCertificateRequestProcessing>d__11.MoveNext()
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in Certify.Management.CertifyManager.<PerformCertificateRequestProcessing>d__10.MoveNext()
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in Certify.Management.CertifyManager.<PerformCertificateRequest>d__7.MoveNext()

**Comment by webprofusion-chrisc** [comment] 2018-10-01 12:10
@glat  thanks - how do you create two certificates at the same time? Do you create the managed certificate without using Request Certificate (just saving it) then hit Renew All?

**Comment by glat** [comment] 2018-10-01 12:46
No. I select first in list and click "request certificate", then I select a second one in list and click again "request certificate".

**Comment by glat** [comment] 2018-10-01 13:37
There's a misunderstanding. So I made a picture and sent it to support. When certificates give renew error and they are red I can only request a new certificate, but I've to do it one by one. Unfortunately this morning I requested all certificates again so in picture they are green, but I do this only when they are red.

**Comment by kd8ssq** [comment] 2018-10-02 19:33
I'm seeing the same error message but the certificates seem to be valid.  The error message states that there was an error installing the certificate, but when I look at the certificate using the "View Certificate" button under "Other Options", the cert is valid and the sites themselves remain secure.

**Comment by webprofusion-chrisc** [comment] 2018-10-03 09:41
The issue seems to be contention committing multiple changes to IIS configuration. New tests have now been created to replicate large installations and a retry strategy has been created to work around exceptions from IIS (we don't know when IIS has finished saving it's settings, so we have to wait and try again). These fixes will be in the next update, which will be soon (within next couple of weeks).

**Comment by glat** [comment] 2018-10-03 09:43
Thanks for your work. It seems the right cause. Can I help by testing a preview?

**Comment by webprofusion-chrisc** [comment] 2018-10-04 11:57
Could you try out the following release candidate? https://certifytheweb.s3.amazonaws.com/downloads/CertifyTheWebSetup_V4.0.9-rc.exe

It has a new retry strategy for binding update issues plus other fixes (Azure DNS, Invalid wildcard domain matches).

**Comment by glat** [comment] 2018-10-04 12:38
Yes, of course, but we've to wait at least tomorrow or some days to check if we get other auto renew errors. I'll update soon.

**Comment by webprofusion-chrisc** [comment] 2018-10-04 23:10
No rush, this won't be fully released until the end of next week, and worst case the bug could still be there in some cases (we retry 3 times with delays). Long term, failed binding updates may need to go into a long lived queue for retries on systems where this strategy is still not enough.

**Comment by kd8ssq** [comment] 2018-10-10 15:28
So I just found out that the reason my sites were still working was that the original cert hadn't expired yet.  More investigation revealed that the renewals created new certificates but never replaced the existing certificates in IIS.  When I try to have Certify (v4.0.9) re-apply the new cert to the binding, the text color in certify changes from Red to Green, but the new cert is still not applied.  Looks like I have to go through all 60 or so sites and change the certs and delete the old ones.

**Comment by webprofusion-chrisc** [comment] 2018-10-10 23:58
@kd8ssq unless your certificates are all expiring today then I would not recommend that course of action. Better to try to get a clearer understanding of whats going wrong and we can try to fix it.  When you Preview does the preview tab say that it will update the binding or not? After the requested cert has gone green what does the log file say? Are there any special considerations? There is currently a possible bug regarding bindings with no hostname, does that affect you?

**Comment by kd8ssq** [comment] 2018-10-11 01:49
Unfortunately most of them were so I had to go through and fix them.  The
new certificates were there, they just weren't being applied to the IIS
bindings and in turn the old carts were not being deleted.  I have a few
coming up for renewal in a couple days, so I'll keep an eye on those.

All the bindings have hostnames.

The app and the log file error stated that the certificate file might not
be valid (but it was).

After I pointed the binding to the new cert (because the update binding
button in the app didn't), then I told the app to update the binding and
the entry went green.  The log stated that the certificate request was
completed and the binding updated in IIS.

I was also made aware by one of my support staff (and I confirmed) that
v4.0.9 no longer automatically assigns the certificates to the binding for
new certificates.

**Comment by glat** [comment] 2018-10-11 07:06
After several days checking I report it's working correctly now. I had just one or two websites with a error. First because of validation failure. About the second I did not understand why it was not renewed and just requested manually a new certificate.

I'll keep checking about auto renew behaviour in next releases.

Thanks for your job.

**Comment by webprofusion-chrisc** [comment] 2018-10-11 09:03
@glat  thanks. I'm currently investigating @kd8ssq observation that the latest certificate does not get used in the updated binding. From my initial checks I believe there may be a bug. Can you check your latest renewed certificates to see if the bindings are actually using the new cert or if they are still using an older one?

**Comment by glat** [comment] 2018-10-11 09:58
Yes, it's true. It's a bug.

I choosed a website which got a renew two days ago (so by using the rc).

The certificate binded in IIS has a issue date of 25 sep and expire date 24 dec.
Then I checked Certificate Manager Console and I've a newer certificate with issue date 9 oct and expire date 7 jan.

So it is not binded correctly because it's the second one which was issued by using the rc.

**Comment by webprofusion-chrisc** [comment] 2018-10-11 12:01
A new version (4.0.10) has now been released. If you install this update your next renewal will fix the certificate binding automatically, however if you can also force the binding to update  (using the new version) using 'Show Advanced Options' > Other Options > Re-apply Certificate Binding.

**Comment by kd8ssq** [comment] 2018-10-11 13:35
Chris,

I applied the patch and the bindings are now applied on new certs.  I've changed the renewal window so I'll have a renewal fire in the morning to test.

Thanks!

**Comment by kd8ssq** [comment] 2018-10-12 14:07
Ok, so I had a few renewals fire across multiple servers this morning and they all assigned the new certificate to the bindings properly.  One thing I noticed was the old cert wasn't deleted.  Isn't Certify supposed to do that?

**Comment by glat** [comment] 2018-10-12 14:17
@kd8ssq Cerify deletes only 1 month AFTER expiration date (chris, correct me if I was wrong).
Here bindings are applied too.

**Comment by kd8ssq** [comment] 2018-10-12 14:19
Sounds good to me.  Just wanted to make sure.  Thanks @glat

**Comment by webprofusion-chrisc** [comment] 2018-10-12 23:57
Yes, the current cleanup process deletes certs 1 month after expiration. The logic there is that some users will have custom or manual uses of a certificate (for other services) so we can't always reliably tell if a cert is still in use. Plan is to make that optional though and have a more instant cleanup available.

**Comment by glat** [comment] 2018-10-13 08:36
This morning I've several web sites with these auto renew error exception:

2018-10-12 18:34:28.368 +02:00 [INF] Requesting Certificate via Let's Encrypt
2018-10-12 18:34:33.415 +02:00 [INF] Completed Certificate Request.
2018-10-12 18:34:33.430 +02:00 [INF] Performing Automated Certificate Binding
2018-10-12 18:35:27.446 +02:00 [INF] System.IO.FileLoadException: Nome file: \\?\C:\Windows\system32\inetsrv\config\applicationHost.config
Errore: Impossibile confermare le modifiche di configurazione poiché il file è stato modificato su disco

   in Certify.Management.Servers.ServerProviderIIS.<AddOrUpdateSiteBinding>d__15.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\Servers\ServerProviderIIS.cs:riga 277
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in Certify.Management.Servers.IISBindingDeploymentTarget.<UpdateBinding>d__3.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\Servers\ServerProviderIIS.cs:riga 789
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in Certify.Core.Management.BindingDeploymentManager.<UpdateBinding>d__8.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\BindingDeploymentManager.cs:riga 380
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in Certify.Core.Management.BindingDeploymentManager.<DeployToAllTargetBindings>d__6.MoveNext() in D:\Work\GIT\certify\src\Certify.Core\Management\BindingDeploymentManager.cs:riga 237

Latest release 4.0.10
Key error is "Errore: Impossibile confermare le modifiche di configurazione poiché il file è stato modificato su disco" which is "Error: Unable to confirm configuration changes because the file has been modified to disk"

I think there's something about the iis commit.

**Comment by webprofusion-chrisc** [comment] 2018-10-14 09:46
@glat thanks for letting me know. If you check the binding itself is it still out of date (pointing to the old certificate)? If so, does manually choosing 'Show Advanced Options' > Other > Re-apply binding fix it? As mentioned earlier we re-try the commit of the IIS changes but we only try 3 times, with a pause between each attempt. We could increase the retry count of make the delay time a custom setting (to allow for the configuration to save). 

Can you try also setting Max auto renewal requests per session to 1 (under Settings). This would mean that the app will only attempt to perform one managed certificate renewal (per hour) and reduce the likelihood of problems caused by IIS being slow to save it's changes.

**Comment by glat** [comment] 2018-10-15 06:29
Yes. The binding is old. I clicked "Reapply binding" button and now binding is with latest certificate.

I also set Max auto renewal requests to 1, as you asked.

**Comment by webprofusion-chrisc** [comment] 2019-02-23 09:30
Closing. Regarding the most recent issue, renewal request are no longer parallel so IIS binding commit errors are no longer likely.

**Closed by webprofusion-chrisc** 2019-02-23 09:30 UTC
