### ISSUE TITLE
PS Scripts Not Running - Execution Policy

### ISSUE THREAD

**Issue by bigben386** [webprofusion/certify#442] opened 2019-02-20 16:59 UTC
Hi,
I am running Certify the web 4.1.4.0 on a windows server 2012 r2 rds server. I am trying to automatically install the letsencrypt certs for the RDS roles but I cannot get the PS scripts to run.  It seems to be related to the PS execution policy. We force remote signed via GPO. I have signed the example scripts and my test scripts with a cert that is trusted by the server and have verified that the scripts run standalone in powershell. This is the error shown in the logs:

> Post-Request Script output:
Error - CmdletInvocationException: Windows PowerShell updated your execution policy successfully, but the setting is overridden by a policy defined at a more specific scope.  Due to the override, your shell will retain its current effective execution policy of RemoteSigned. Type "Get-ExecutionPolicy -List" to view your execution policy settings. For more information please see "Get-Help Set-ExecutionPolicy".
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at Certify.Management.PowerShellManager.<RunScript>d__0.MoveNext() in C:\Work\GIT\certify\src\Certify.Shared\Management\PowerShellManager.cs:line 48

I get a similar error when clicking the test button. Is there a way to disable the execution policy check so that my scripts will run?

Thanks

**Comment by webprofusion-chrisc** [comment] 2019-02-21 04:09
Hi, this is most likely a limitation caused by the way we invoke powershell (we set execution policy to 'Unrestricted'). Unfortunately in this case that means we will need to create an update with a config option for you to set, so there's nothing you can do immediately (outside of building your own copy of the app and copying over Certify.Shared.dll).

We should have a new release out within the next week.

**Comment by mcbsys** [comment] 2019-05-13 17:01
Same issue here with latest Certify the Web version 4.1.6 under Windows Server 2016 with Essentials. I see this was flagged as a bug and closed. Was it fixed? Is there something I need to do to tell Certify to _not_ issue `Set-ExecutionPolicy Unrestricted` before running the script?

**Comment by bigben386** [comment] 2019-05-13 17:16
This took me a while to figure out too. You need to change %programdata%\Certify\serviceconfig.json. I changed the powershellexecutionpolicy line to
 "PowershellExecutionPolicy": "RemoteSigned"
since that is our GPO'd execution policy.

**Comment by mcbsys** [comment] 2019-05-13 17:28
Thanks. Tried that. First test succeeded. After saving, going back in, and testing again, it started failing with the same error. Then I got a bunch of "Waiting for Remote Desktop Services to Stop" messages. Then it worked again.

**Comment by mcbsys** [comment] 2020-09-04 16:40
With C:\ProgramData\Certify\serviceconfig.json set to RemoteSigned as suggested by @bigben386, this worked several times with versions 4.1.5, 4.1.6, and 4.1.8. Now after updating to 5.1.3, it's broken again. There's a different path and error line than was originally reported above. The message makes it sounds like it will just use the active execution policy, which would be fine, but instead it seems to cause the execution to abort. Can this be fixed?

    2020-09-03 21:15:04.360 -07:00 [ERR] Error - CmdletInvocationException: Windows PowerShell updated your execution policy successfully, but the setting is overridden by a policy defined at a more specific scope.  Due to the override, your shell will retain its current effective execution policy of RemoteSigned. Type "Get-ExecutionPolicy -List" to view your execution policy settings. For more information please see "Get-Help Set-ExecutionPolicy".
       at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
       at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
       at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
       at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
       at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
       at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
       at Certify.Management.PowerShellManager.InvokePowershell(CertificateRequestResult result, String executionPolicy, String scriptFile, Dictionary`2 parameters, String scriptContent, PowerShell shell) in C:\Work\GIT\certify_dev\certify\src\Certify.Shared.Compat\PowerShellManager.cs:line 118
       at Certify.Management.PowerShellManager.<RunScript>d__0.MoveNext() in C:\Work\GIT\certify_dev\certify\src\Certify.Shared.Compat\PowerShellManager.cs:line 90

**Comment by webprofusion-chrisc** [comment] 2020-09-05 06:09
@mcbsys thanks, the powershell support in 5.x is significantly modified ( you can run as different users etc) so there is a chance we have a new bug. I'll investigate.

**Comment by webprofusion-chrisc** [comment] 2020-09-05 06:14
Yes, we're not passing in the preferred script execution policy, fix in next release early next week.

**Comment by webprofusion-chrisc** [comment] 2020-09-07 06:09
Fixed v5.1.5

**Comment by Absoblogginlutely** [comment] 2020-10-19 21:14
Looks like this has re-occurred in v5.1.10
Our configuration was set to RemoteSigned and get the same error.
Fixed by setting "C:\ProgramData\Certify\serviceconfig.json" and then 
  "PowershellExecutionPolicy": "remotesigned"

**Comment by mcbsys** [comment] 2020-10-19 22:00
@Absoblogginlutely, it's a bit unclear, but I think the only workaround is to set C:\ProgramData\Certify\serviceconfig.json to RemoteSigned. Did it work when you set that?

@webprofusion-chrisc, can the program just use the system-defined execution policy, i.e. let it behave as stated in this error message? (Treat that as a warning, not a a failure.)

`"CmdletInvocationException: Windows PowerShell updated your execution policy successfully, but the setting is overridden by a policy defined at a more specific scope.  Due to the override, your shell will retain its current effective execution policy of RemoteSigned. Type "Get-ExecutionPolicy -List" to view your execution policy settings. For more information please see "Get-Help Set-ExecutionPolicy".`

**Comment by Absoblogginlutely** [comment] 2020-10-19 22:47
@mcbsys it worked for the first script we added to the install. However when we added a second script to the same job and them ran a test  on the second script it generated the same error which is even odder behaviour!

**Comment by webprofusion-chrisc** [comment] 2020-10-20 00:24
Thanks I'll do some investigation today. From a quick check I believe we are passing the preferred execution policy defined in `serviceconfig.json`.

Recently there's been a lot of changes around trying to support different levels of user impersonation and that combined with this suggest we should perhaps just spawn powershell in a new process instead of running it embedded in-process.

**Comment by webprofusion-chrisc** [comment] 2020-10-20 00:27
@Absoblogginlutely regarding your settings, it sounds like you didn't have RemoteSigned specified in serviceconfig.json, then you added it and it started working? i.e. it was working the same as it normally does and you hadn't yet set the config?

**Comment by webprofusion-chrisc** [comment] 2020-10-20 01:19
@Absoblogginlutely you mentioned adding multiple tasks and one of them not working after the first one ran - is that reproduceable and if so do you have an example script?

**Comment by webprofusion-chrisc** [comment] 2020-10-20 01:42
Reviewing this some more we were defaulting to Unrestricted on purpose, we could possibly default to `Bypass` instead. From what I can tell this problem is actually fixed and working in the current version as long as you set your policy in serviceconfig.json? If nobody can demonstrate otherwise I'll leave it as there is a risk of breaking stuff for other users.

**Comment by Absoblogginlutely** [comment] 2020-10-20 10:43
THanks for the prompt replies @webprofusion-chrisc 
The sequence of events yesterday were as follows. 
Install 5.1.10 using chocolatey. 
Set up cert request. Add task 1 (rdgw script).
Failed with the powershell restriction.
Update serviceserviceconfig.json ro use remotesigned.
Worked
Add second task to set rdpcollection cert (I'll attach later)
Failed on second task when pushing the play button
Added comment to github

**Comment by webprofusion-chrisc** [comment] 2020-10-20 10:57
Thanks, did you restart the Certify.Service background service after updating the serviceconfig.json? Note also that most script won't work until you've completed your first cert request (so that you have a cert file to play with).

**Comment by Absoblogginlutely** [comment] 2020-10-20 12:59
In the steps above yesterday I did not restart the service. This morning I connected to the server, opened ctw and both tasks showed as success with a runtime of yesterday (when it had failed).
I ran both tasks this morning and got the same messages along with a status of failed for both. I exited the app, restarted the service, opened the app and see the status now shows the first app success and the second fail - even though they had not actually run, so I'm wondering if the status is not being updated correctly?
![image](https://user-images.githubusercontent.com/21364480/96587943-ff32de80-12b0-11eb-9362-75e243ec4f0b.png)

I then retried running the script (now that the service was restarted. The first script ran successfully.no prompt about the policy restrictions.
Reran the second script - also succeeded. Restarting the service was obviously the trick after updating serviceserviceconfig.json

**Comment by mcbsys** [comment] 2020-10-20 18:41
Not sure if I've followed all those details but wanted to offer a higher-level thought on design. It would be nice to not have to manually set a policy in the JSON file. I can think of two ways that could be handled:

1. If the system still has the default policy (Restricted?), override with Bypass for the execution of the script; otherwise use the configured policy. It's fine to emit a warning if the system policy is used, but don't fail the script just because of that. In this scenario, if the non-default base policy is too restrictive, the script _should_ fail; it has violated the sysadmin's intent. That could still be rectified by the JSON policy override.

2.  Always set to Bypass for the duration of the script. It bugs me that PowerShelll allows this, as it basically makes the ExecutionPolicy useless in blocking viruses from using PowerShell. But it's there and I've seen another script runner do it.

**Comment by webprofusion-chrisc** [comment] 2020-10-22 02:11
@Absoblogginlutely I can't reproduce this - can you confirm what your machine level execution policy is and how it is set (GPO?) - I'm guessing that we are incorrectly logging a warning as an error. 

@mcbsys our current default is Unrestricted and it has been for a long time, Bypass may be better but we will need to leave that to 5.2 beta as it will require some beta testing.

Could you both possibly run `Get-ExecutionPolicy -List` in the 64-bit powershell prompt and tell me the output so I can recreate the same hierarchy you have? On the machine I'm testing on its:

```
        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy       Undefined
   UserPolicy       Undefined
      Process       Undefined
  CurrentUser    RemoteSigned
 LocalMachine    RemoteSigned
```

**Comment by mcbsys** [comment] 2020-10-22 03:59
```
PS C:\> Get-ExecutionPolicy -List

        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy    RemoteSigned
   UserPolicy    RemoteSigned
      Process       Undefined
  CurrentUser       Undefined
 LocalMachine    RemoteSigned
```

**Comment by webprofusion-chrisc** [comment] 2020-10-22 04:16
@mcbsys thanks! In the latest version (5.1.11) you can set ExecutionPolicy to "" (a blank string) in the config (then restart the certify background service) - that way the current execution policy will always be used and we won't attempt to call Set-ExecutionPolicy in the process or to use our normal "Unrestricted" policy.

@Absoblogginlutely I was able to reproduce the same error and it's fixed by the above method (so that we don't attempt to set the policy).

**Comment by Absoblogginlutely** [comment] 2020-10-22 17:09
Thanks @webprofusion-chrisc, I can confirm my execution policies are set in the same as mcbsys. There are a few things that could be setting this although it's typically user setting. After upgrading to 5.1.11 I am no longer getting these issues (with serviceserviceconfig.json set to "")

**Comment by mcbsys** [comment] 2020-10-23 18:04
Okay I've upgraded to 5.1.11, changed the PowershellExecutionPolicy from "RemoteSigned" to "" in both of these files, then restarted the Certify SSL Manager Service.

C:\ProgramData\Certify\serviceconfig.json
C:\ProgramData\Certify\CustomScripts\serviceconfig.json

I see the discussion so far has been about the first file. What is the purpose of the second file?

**Comment by webprofusion-chrisc** [comment] 2020-10-25 03:42
@mcbsys the `CustomScripts\serviceconfig.json` is something you made up and has nothing to do with Certify  :) I reckon you just copied it in there accidentally (that's also your own folder, we don't create that), it won't be doing anything for Certify though.

**Comment by mcbsys** [comment] 2020-10-25 14:35
@webprofusion-chrisc Oops, you're right. It's actually in an independent folder I created under ProgramData:

C:\ProgramData\CertifyCustomScripts\serviceconfig.json

Had I but browsed that folder (instead of just searching or serviceconfig.json), I would have found the readme that I wrote in 2019:  "This serviceconfig.json must be copied back to %ProgramData%\Certify whenever Certify the Web is updated." In the meantime, I think that program updates no longer overwrite the customized .json file?

**Comment by webprofusion-chrisc** [comment] 2020-10-26 00:30
@mcbsys any json file update we make would read the json first, make the change then write it back, so the only thing that would/should ever be lost would be custom data fields that don't exist in our object model. So you shouldn't have needed to do this at all - I don't remember ever hearing about it from anyone as an issue and I don't believe it's an issue now. The app setup process has never written that file but the app itself does work with it.

**Comment by mcbsys** [comment] 2020-10-26 02:06
@webprofusion-chrisc Great, thanks. Maybe I was just preemptively saving my custom version just in case.

**Comment by webprofusion-chrisc** [comment] 2021-02-17 08:27
Closing. No further issues/discussions have been raised against our current defaults.

**Closed by webprofusion-chrisc** 2021-02-17 08:27 UTC
Labels: bug
